# Generated by Django 4.1.7 on 2025-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='种类ID'),
        ),
        migrations.AddField(
            model_name='image',
            name='colors',
            field=models.JSONField(default=list),
        ),
    ]
